export const codeTypes = {
  UPDATE_CODE: 'UPDATE_CODE',
  CODE_RUNNING: 'CODE_RUNNING',
  CODE_RUN_SUCCESS: 'CODE_RUN_SUCCESS',
  CODE_RUN_ERROR: 'CODE_RUN_ERROR',
  UPDATE_EDITOR_THEME: 'UPDATE_EDITOR_THEME',
  LOAD_CODE_SAMPLE: 'LOAD_CODE_SAMPLE'
};
